---
- name: Create Image and Re-Create Docker Container
  hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: build container image
    docker_image:
      name: myphpapplication:v1.0
      build:
        path: /tmp/project/
      source: build
      state: present
      force_source: yes
  - name: Re-create container
    docker_container:
      name: myphpapp
      image: myphpapplication:v2.0
      state: started
      recreate: yes
      ports:
      # Publish container port 80 as host port 8080
      - "8080:80"
