---
- name: Install Docker, Clone git repository, Create Image and Start Container
  hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install docker
    yum:
      name: docker 
      state: present
  - name: Start Docker Service
    service:
      name: docker 
      state: started
      enabled: yes
  - name: Install git
    yum:
      name: git
      state: present
      update_cache: yes
  - name: Git checkout
    git:
      repo: 'https://github.com/paul5-edureka/projCert.git'
      dest: /tmp/project
  - name: build container image
    docker_image:
      name: myphpapplication:v1.0
      build:
        path: /tmp/project/
        source: build
